apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: elamendevopsconcept 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elamendevopsconcept 
    spec:
      containers:
        - name: elamendevopsconcept 
          image: devopsconceptregistry.azurecr.io/elamendevopsconcept
          ports:
          - containerPort: 80